\documentclass{beamer}

\usepackage{amsmath, microtype, amsthm}
\usepackage{graphicx}
\usepackage{parskip}

\frenchspacing

\usetheme{default}
\usecolortheme{orchid}

<<opts, echo = F, message = F>>=
require(knitr)
opts_chunk$set(warning = F, message = F, highlight = T, background = 'white', size = 'scriptsize', echo = F, fig.height = 5, fig.width = 5)
@

\title{A four part treatise on Gygaxian naturalism}
\author{Peter D Smits, Wiz}
\institute{
Department of Arcane Biology\\
The Unseen University
}
\scriptsize{\date{\today}}

\AtBeginSection[]
{
  \begin{frame}
    \frametitle{Table of Contents}
    \tableofcontents[currentsection]
  \end{frame}
}


\begin{document}

\begin{frame}
\titlepage
\end{frame}

\begin{frame}
  \frametitle{First things first\dots}

  \huge{I put on my robe and wizard hat\dots}

  \footnotesize{Note: Robe missing due to budgetary constraints.}

\end{frame}

\begin{frame}
  \frametitle{Outline}
  \tableofcontents
\end{frame}


\section{Introduction}
%\subsection{Necessary History}
\begin{frame}
  \frametitle{Origin of Gygaxian Naturalism}
  \begin{columns}
    \begin{column}{0.5\textwidth}
      \includegraphics[width = \textwidth, keepaspectratio = true]{gygax}
    \end{column}
    \begin{column}{0.5\textwidth}
      \includegraphics[width = \textwidth, keepaspectratio = true]{whitebox}
    \end{column}
  \end{columns}
  % the original pamphletes
  % maybe show some of the original style art

\end{frame}

\begin{frame}
  \frametitle{Central Texts}
  % monster manuals for the different editions
  % stess how AD&D1 is probably the best because least edits
  \noindent
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{mm1}\hspace{0.2\textwidth}%
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{mm2}\\[2em]
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{mm35}\hspace{0.2\textwidth}%
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{mm4}\par
  
\end{frame}

\begin{frame}
  \frametitle{Other Important Works}
  \noindent
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{hack}\hspace{0.2\textwidth}%
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{nomicon}\\[2em]
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{path}\hspace{0.2\textwidth}%
  \includegraphics[height = 0.4\textheight, keepaspectratio = true]{redbox}\par

\end{frame}

\begin{frame}
  \frametitle{Consistent Questions}

\end{frame}


\section{Goblinoid Phylogeny}
\begin{frame}
  \frametitle{How many goblinoids are there?}
  
  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
        \item Goblins
        \item Hobgoblins
        \item Bugbears
        \item Blues
        \\~\\
        \item Related taxa
        \begin{itemize}
          \item Orcs
          \item Ogres
          \item Ettins
          \item other monstrous humanoids
        \end{itemize}
      \end{itemize}
    \end{column}

    \begin{column}{0.5\textwidth}
      \includegraphics[width = \textwidth, keepaspectratio = true]{goblinoids}
    \end{column}

  \end{columns}

\end{frame}

\begin{frame}
  \frametitle{Materials and Methods}

  \begin{columns}
    \begin{column}{0.5\textwidth}
      
    \end{column}

    \begin{column}{0.5\textwidth}

    \end{column}

  \end{columns}

\end{frame}

\begin{frame}
  \frametitle{Phylogeny}
<<gob-phy>>=
require(ape)

species <- c('Goblins', 'Blue', 'Hobgoblins', 'Bugbears', 'Orcs', 'Giants', 
             'Ettin', 'Troll', 'Xvarts', 'Gibberlings', 'Kobolds', 'Gnoll',
             'Dragonkin', 'Troglodyte')

gob <- read.nexus('goblins.nex')
gob$tip.label <- species

plot(gob, edge.width = 1, adj = 0.1)
@
\end{frame}


\section{Adaptation in Elves}
\begin{frame}
  \frametitle{History of our Knowledge}
  \includegraphics[height = 0.5\textheight, keepaspectratio = true]{elf_1}

  At least 5 species/races of elves known from the most recent survey.

\end{frame}

\begin{frame}
  \frametitle{Adaptive or Cultural?}
  \includegraphics[height = 0.5\textheight, keepaspectratio = true]{elf_2}

  All adapated to very different environments, but physiologically and culturally.

\end{frame}

\begin{frame}
  \frametitle{Magic!!!}
  \includegraphics[width = \textwidth, keepaspectratio = true]{wizard_comic}

\end{frame}

\begin{frame}
  \frametitle{How else do explain\dots}
  \includegraphics[width = \textwidth, keepaspectratio = true]{owlbear_1}

\end{frame}


\section{Species concepts with Dragons}
\begin{frame}
  \frametitle{}

\end{frame}


\section{Dungeon Ecology}
\begin{frame}
  \frametitle{}

\end{frame}


\begin{frame}
  \frametitle{Acknowledgements}

  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
        \item All my players though out the years
          \begin{itemize}
            \item The Crew of the Talking Pussy
            \item The Fancy Boots Brigade of Ruins
            \item New Corden Adventurers (temporary name)
            \item and all those without names
          \end{itemize}
        \item 
      \end{itemize}

    \footnotesize{source avaliable on GitHub}

    \end{column}

    \begin{column}{0.5\textwidth}
      \includegraphics[width = \textwidth, keepaspectratio = true]{unseen}

    \end{column}

  \end{columns}

\end{frame}


\end{document}
