library(igraph)
library(stringr)

load('../data/star_trek_graph.rdata')

ranks <- page.rank(g)
order.ranks <- rev(sort(ranks$vector))
#degree(g)
#centralization.degree(g)
#closeness(g)
#centralization.closeness(g)
#betweenness(g)
#centralization.betweenness(g)
#alpha.centrality(g)
#diameter(g)
#get.diameter(g)
#farthest.nodes(g)
#eccentricity(g)
#radius(g)
#graph.diversity(g)
#info <- infomap.community(g, nb.trials = 1000)
